import { z } from "zod";

// The contract between stored content and the activity renderers. `questions.content`
// and `questions.answer` are JSON in the database; these schemas validate them on import
// (scripts/content/import.ts) and again when a lesson is loaded, so a malformed question
// is skipped and reported instead of breaking a child's lesson.
//
// Adding a question type = add its schema here, a row in activity_types, an evaluator
// branch in src/lib/learning/evaluate.ts and a renderer in src/features/activities.

const text = (max: number) => z.string().trim().min(1).max(max);

export const choiceOptionSchema = z.object({
  id: z.string().regex(/^[a-z0-9-]{1,40}$/),
  // Up to a short sentence ("Which sentence makes sense?").
  text: z.string().trim().max(80).optional(),
  emoji: z.string().max(16).optional(),
  // What to say when the option's speaker is tapped (defaults to `text`).
  speech: z.string().trim().max(120).optional(),
});

export const introContentSchema = z.object({
  heading: text(80),
  body: z.string().trim().max(400).default(""),
  speech: z.string().trim().max(400).default(""),
  display: z.string().trim().max(40).optional(),
  examples: z
    .array(
      z.object({
        text: text(40),
        emoji: z.string().max(16).optional(),
        // Letters to highlight inside `text`, e.g. "sh" in "ship".
        highlight: z.string().max(8).optional(),
      }),
    )
    .max(8)
    .default([]),
  // Letters only: the letter's NAME and its SOUND, shown and played as two different
  // things ("bee" is the name; /b/ "buh" is the sound).
  letter: z
    .object({
      upper: z.string().trim().min(1).max(2),
      lower: z.string().trim().min(1).max(2),
      name: text(20),
      nameSpeech: text(40),
      soundLabel: text(8),
      soundSpeech: text(40),
    })
    .optional(),
});

export const choiceContentSchema = z.object({
  // Shown above the options: a letter, a word, or a short passage to read.
  display: z.string().trim().max(300).optional(),
  // Hide option labels so the child must rely on the picture/sound (listen-and-choose).
  hideOptionText: z.boolean().default(false),
  options: z.array(choiceOptionSchema).min(2).max(6),
});

// Spelling (Phase 6): a word's grapheme split as the spelling engine sees it (ship =
// sh·i·p with each grapheme's phonemes and phonics pattern), progressive hints, and the
// positions of a word's irregular part. Generated by the templates from the word bank.
export const spellingSegmentSchema = z.object({
  grapheme: z.string().regex(/^[a-z']{1,6}$/),
  phonemes: z.array(z.string().regex(/^[A-Z]{1,3}$/)).max(4).optional(),
  patternCode: z.string().max(40).nullable().optional(),
  patternType: z.string().max(40).nullable().optional(),
});
export const spellingHintSchema = z.object({
  kind: z.enum(["listen", "listen_slow", "sounds", "first_sound", "letters", "pattern", "tricky", "custom"]),
  text: text(120),
  speech: z.string().trim().max(160).default(""),
  // What to show with the hint ("sh _ _").
  show: z.string().trim().max(60).optional(),
});
const spellingSplit = z.array(spellingSegmentSchema).min(1).max(16).optional();
const spellingHints = z.array(spellingHintSchema).max(4).default([]);
// A sound the child can tap to hear (a phoneme label such as "sh", never the letters).
const heardSoundSchema = z.object({ label: text(8), sayAs: text(40) });

export const missingLetterContentSchema = z
  .object({
    word: text(40),
    emoji: z.string().max(16).optional(),
    // "sound": the missing part is a sound (MISSING_SOUND) — its sound can be played.
    mode: z.enum(["letter", "sound"]).default("letter"),
    sound: heardSoundSchema.optional(),
    split: spellingSplit,
    hints: spellingHints,
    parts: z
      .array(z.union([z.object({ text: text(20) }), z.object({ blank: z.literal(true) })]))
      .min(2)
      .max(8),
    choices: z.array(text(8)).min(2).max(6),
  })
  .refine((c) => c.parts.filter((p) => "blank" in p).length === 1, {
    message: "missing-letter content needs exactly one blank part",
  });

export const wordBuilderContentSchema = z.object({
  emoji: z.string().max(16).optional(),
  // What to say as the target word (defaults to the accepted answer).
  speech: z.string().trim().max(60).optional(),
  tiles: z.array(text(8)).min(2).max(12),
  slots: z.number().int().min(1).max(10),
  // Show the tiles joined slowly (C → A → T → CAT) before building.
  demonstrateBlend: z.boolean().default(false),
  // "scrambled": the tiles are the word's own letters, mixed up (SCRAMBLED_WORD).
  mode: z.enum(["build", "scrambled"]).default("build"),
  split: spellingSplit,
  hints: spellingHints,
});

export const sentenceBuilderContentSchema = z.object({
  emoji: z.string().max(16).optional(),
  tokens: z.array(text(24)).min(2).max(14),
});

// Type a word: listen and type (picture + word), dictation (the word only, limited
// replays) or sounds to word (tap the sounds, then write the word they make).
export const spellingContentSchema = z.object({
  emoji: z.string().max(16).optional(),
  speech: z.string().trim().max(60).optional(),
  hint: z.string().trim().max(120).optional(),
  mode: z.enum(["listen", "dictation", "sounds"]).default("listen"),
  sounds: z.array(heardSoundSchema).min(1).max(10).optional(),
  // Letters for tile input (the word's letters plus a few others).
  tiles: z.array(text(6)).min(2).max(16).optional(),
  split: spellingSplit,
  // Grapheme positions of the word's irregular part ("ai" in said = [1]).
  irregular: z.array(z.number().int().min(0).max(15)).max(6).default([]),
  hints: spellingHints,
});

// Hear a sentence, write it. Checked word by word; capitals and the end mark only when
// the answer asks for them (requirePunctuation).
export const sentenceDictationContentSchema = z.object({
  emoji: z.string().max(16).optional(),
  speech: text(200),
  wordCount: z.number().int().min(1).max(20),
  hints: spellingHints,
});

const itemId = z.string().regex(/^[a-z0-9-]{1,40}$/);

// Match pairs (left ↔ right): a picture to its word, a capital to its small letter.
export const matchItemSchema = z.object({
  id: itemId,
  // A word, or a child-friendly meaning (word → meaning matching).
  text: z.string().trim().max(80).optional(),
  emoji: z.string().max(16).optional(),
  speech: z.string().trim().max(120).optional(),
});
export const matchContentSchema = z.object({
  left: z.array(matchItemSchema).min(2).max(6),
  right: z.array(matchItemSchema).min(2).max(6),
});

// Sort items into 2–4 groups ("sh" words / "ch" words).
export const sortContentSchema = z.object({
  groups: z
    .array(z.object({ id: itemId, label: text(40), emoji: z.string().max(16).optional() }))
    .min(2)
    .max(4),
  items: z.array(matchItemSchema).min(2).max(10),
});

// Drag words from a bank into the blanks of a sentence or word ("The ___ sat.").
export const dragDropContentSchema = z
  .object({
    emoji: z.string().max(16).optional(),
    parts: z
      .array(z.union([z.object({ text: text(60) }), z.object({ blank: z.literal(true) })]))
      .min(2)
      .max(12),
    bank: z.array(text(24)).min(2).max(8),
  })
  .refine((c) => c.parts.some((p) => "blank" in p), { message: "drag-drop content needs a blank" });

// Reading comprehension: the passage lives in the activity config (a story, shared by its
// questions); each question is a choice about it — multiple choice, true/false (two options
// "yes"/"no") or a word's meaning in the text. `ref` points at the sentence that answers it
// (paragraph and sentence index), highlighted after answering so the child can look back.
export const passageRefSchema = z.object({
  paragraph: z.number().int().min(0).max(40),
  sentence: z.number().int().min(0).max(40),
});
export const readingContentSchema = choiceContentSchema.extend({
  format: z.enum(["choice", "true_false", "word_meaning"]).default("choice"),
  // The word asked about in a word-meaning question (highlighted in the text).
  focusWord: z.string().trim().max(40).optional(),
  ref: passageRefSchema.optional(),
});

// Choose every right answer ("Which animals were in the story?"). Two or more are right.
export const selectAllContentSchema = choiceContentSchema.extend({
  options: z.array(choiceOptionSchema).min(3).max(6),
  ref: passageRefSchema.optional(),
});

// Put the events of a story in order. Events are shown in the stored order (shuffled by
// the importer so they never start in the right order).
export const orderEventsContentSchema = z.object({
  events: z
    .array(z.object({ id: itemId, text: text(120), emoji: z.string().max(16).optional() }))
    .min(3)
    .max(6),
});

// Read a text (the story in the activity config): listen first or read first, tap a word
// to hear it, re-read. Unscored; the device reports a reading session instead.
export const readPassageContentSchema = z.object({
  mode: z.enum(["listen_first", "read_first", "reread"]).default("read_first"),
  // Highlight each word (youngest) or each sentence while the text is read aloud.
  highlight: z.enum(["word", "sentence"]).default("sentence"),
  // Asked after reading, as the child's own check ("How was that?"). Never scored.
  selfCheck: z.boolean().default(true),
});

// Write a word or finish a sentence, with a word bank to copy from.
export const writingContentSchema = z.object({
  emoji: z.string().max(16).optional(),
  starter: z.string().trim().max(80).optional(),
  wordBank: z.array(text(24)).min(2).max(8),
  hint: z.string().trim().max(120).optional(),
});

// Trace a letter with a finger; scored by how much of the letter the strokes cover.
export const tracingContentSchema = z.object({
  letter: z.string().trim().min(1).max(2),
  speech: z.string().trim().max(60).optional(),
});

// A sound unit a child can tap to hear (a grapheme segment, or a phoneme).
const soundUnitSchema = z.object({
  grapheme: text(6),
  sayAs: z.string().trim().max(40),
});

// Blending: tap each sound, blend them (slow or normal), then choose the word they make.
// The word itself is only spoken after answering.
export const blendSoundsContentSchema = z.object({
  emoji: z.string().max(16).optional(),
  units: z.array(soundUnitSchema).min(1).max(8),
  options: z.array(choiceOptionSchema).min(2).max(4),
});

// Segmenting: hear a word, say how many sounds it has, then pick those sounds in order.
// Sound cards are phonemes (shown as /sh/), never the word's letters.
export const segmentWordContentSchema = z.object({
  word: text(40),
  emoji: z.string().max(16).optional(),
  speech: text(60),
  sounds: z
    .array(z.object({ id: itemId, label: text(8), sayAs: text(40) }))
    .min(2)
    .max(10),
  maxCount: z.number().int().min(2).max(8),
});

// Find the pattern (e.g. the digraph) in a written word by tapping its letters.
export const findPatternContentSchema = z.object({
  word: z.string().trim().regex(/^[a-z']{2,20}$/),
  emoji: z.string().max(16).optional(),
  speech: z.string().trim().max(60).optional(),
  // What to look for, as shown to the child ("sh").
  target: text(8),
});

export const acceptedAnswerSchema = z.object({
  accepted: z.array(text(120)).min(1).max(10),
});

export const sentenceAnswerSchema = acceptedAnswerSchema.extend({
  accepted: z.array(text(200)).min(1).max(5),
  requirePunctuation: z.boolean().default(false),
});

export const sequenceAnswerSchema = z.object({
  acceptedSequences: z
    .array(z.array(text(24)).min(1).max(14))
    .min(1)
    .max(5),
});

export const pairsAnswerSchema = z.object({
  pairs: z.array(z.tuple([itemId, itemId])).min(1).max(10),
});

export const coverageAnswerSchema = z.object({
  minCoverage: z.number().int().min(30).max(95),
});

// Select-all: every right option id (order does not matter).
export const selectAllAnswerSchema = z.object({
  correct: z.array(z.string().regex(/^[a-z0-9-]{1,40}$/)).min(2).max(5),
});

export const valueResponseSchema = z.object({ value: z.string().max(200) });
export const sequenceResponseSchema = z.object({ sequence: z.array(z.string().max(40)).max(20) });
export const pairsResponseSchema = z.object({
  pairs: z.array(z.tuple([z.string().max(40), z.string().max(40)])).max(10),
});
export const coverageResponseSchema = z.object({ coverage: z.number().min(0).max(100) });
export const responseSchema = z.union([
  valueResponseSchema,
  sequenceResponseSchema,
  pairsResponseSchema,
  coverageResponseSchema,
]);
export type QuestionResponse = z.infer<typeof responseSchema>;

// Each type's content schema, answer schema (null = unscored) and response schema.
export const questionTypeSchemas = {
  INTRO: { content: introContentSchema, answer: null, response: null },
  MULTIPLE_CHOICE: {
    content: choiceContentSchema,
    answer: acceptedAnswerSchema,
    response: valueResponseSchema,
  },
  LISTEN_AND_CHOOSE: {
    content: choiceContentSchema,
    answer: acceptedAnswerSchema,
    response: valueResponseSchema,
  },
  PICTURE_MATCH: {
    content: choiceContentSchema,
    answer: acceptedAnswerSchema,
    response: valueResponseSchema,
  },
  MISSING_LETTER: {
    content: missingLetterContentSchema,
    answer: acceptedAnswerSchema,
    response: valueResponseSchema,
  },
  WORD_BUILDER: {
    content: wordBuilderContentSchema,
    answer: acceptedAnswerSchema,
    response: sequenceResponseSchema,
  },
  SENTENCE_BUILDER: {
    content: sentenceBuilderContentSchema,
    answer: sequenceAnswerSchema,
    response: sequenceResponseSchema,
  },
  SPELLING: { content: spellingContentSchema, answer: acceptedAnswerSchema, response: valueResponseSchema },
  MATCH: { content: matchContentSchema, answer: pairsAnswerSchema, response: pairsResponseSchema },
  SORT: { content: sortContentSchema, answer: pairsAnswerSchema, response: pairsResponseSchema },
  DRAG_DROP: {
    content: dragDropContentSchema,
    answer: sequenceAnswerSchema,
    response: sequenceResponseSchema,
  },
  READING: { content: readingContentSchema, answer: acceptedAnswerSchema, response: valueResponseSchema },
  WRITING: { content: writingContentSchema, answer: acceptedAnswerSchema, response: valueResponseSchema },
  TRACING: { content: tracingContentSchema, answer: coverageAnswerSchema, response: coverageResponseSchema },
  BLEND_SOUNDS: {
    content: blendSoundsContentSchema,
    answer: acceptedAnswerSchema,
    response: valueResponseSchema,
  },
  SEGMENT_WORD: {
    content: segmentWordContentSchema,
    answer: sequenceAnswerSchema,
    response: sequenceResponseSchema,
  },
  // The answer is the letters' span in the word: "start-end" (0-based, inclusive).
  FIND_PATTERN: {
    content: findPatternContentSchema,
    answer: acceptedAnswerSchema,
    response: valueResponseSchema,
  },
  SENTENCE_DICTATION: {
    content: sentenceDictationContentSchema,
    answer: sentenceAnswerSchema,
    response: valueResponseSchema,
  },
  READ_PASSAGE: { content: readPassageContentSchema, answer: null, response: null },
  // The response is the chosen option ids (`sequence`, any order).
  SELECT_ALL: { content: selectAllContentSchema, answer: selectAllAnswerSchema, response: sequenceResponseSchema },
  ORDER_EVENTS: {
    content: orderEventsContentSchema,
    answer: sequenceAnswerSchema,
    response: sequenceResponseSchema,
  },
} as const;

export type SupportedQuestionType = keyof typeof questionTypeSchemas;

export function isSupportedQuestionType(type: string): type is SupportedQuestionType {
  return Object.hasOwn(questionTypeSchemas, type);
}

export type IntroContent = z.infer<typeof introContentSchema>;
export type ChoiceContent = z.infer<typeof choiceContentSchema>;
export type MissingLetterContent = z.infer<typeof missingLetterContentSchema>;
export type WordBuilderContent = z.infer<typeof wordBuilderContentSchema>;
export type SentenceBuilderContent = z.infer<typeof sentenceBuilderContentSchema>;
export type SpellingContent = z.infer<typeof spellingContentSchema>;
export type MatchContent = z.infer<typeof matchContentSchema>;
export type SortContent = z.infer<typeof sortContentSchema>;
export type DragDropContent = z.infer<typeof dragDropContentSchema>;
export type ReadingContent = z.infer<typeof readingContentSchema>;
export type WritingContent = z.infer<typeof writingContentSchema>;
export type TracingContent = z.infer<typeof tracingContentSchema>;
export type BlendSoundsContent = z.infer<typeof blendSoundsContentSchema>;
export type SegmentWordContent = z.infer<typeof segmentWordContentSchema>;
export type FindPatternContent = z.infer<typeof findPatternContentSchema>;
export type SentenceDictationContent = z.infer<typeof sentenceDictationContentSchema>;
export type SelectAllContent = z.infer<typeof selectAllContentSchema>;
export type OrderEventsContent = z.infer<typeof orderEventsContentSchema>;
export type ReadPassageContent = z.infer<typeof readPassageContentSchema>;
export type PassageRef = z.infer<typeof passageRefSchema>;
export type SelectAllAnswer = z.infer<typeof selectAllAnswerSchema>;
export type SpellingSegmentContent = z.infer<typeof spellingSegmentSchema>;
export type SpellingHintContent = z.infer<typeof spellingHintSchema>;
export type AcceptedAnswer = z.infer<typeof acceptedAnswerSchema>;
export type SequenceAnswer = z.infer<typeof sequenceAnswerSchema>;
export type PairsAnswer = z.infer<typeof pairsAnswerSchema>;
export type CoverageAnswer = z.infer<typeof coverageAnswerSchema>;
export type SentenceAnswer = z.infer<typeof sentenceAnswerSchema>;
export type AnswerSpec =
  | AcceptedAnswer
  | SentenceAnswer
  | SequenceAnswer
  | PairsAnswer
  | CoverageAnswer
  | SelectAllAnswer;

export type ParsedQuestion =
  | { type: "INTRO"; content: IntroContent; answer: null }
  | {
      type: "MULTIPLE_CHOICE" | "LISTEN_AND_CHOOSE" | "PICTURE_MATCH";
      content: ChoiceContent;
      answer: AcceptedAnswer;
    }
  | { type: "MISSING_LETTER"; content: MissingLetterContent; answer: AcceptedAnswer }
  | { type: "WORD_BUILDER"; content: WordBuilderContent; answer: AcceptedAnswer }
  | { type: "SENTENCE_BUILDER"; content: SentenceBuilderContent; answer: SequenceAnswer }
  | { type: "SPELLING"; content: SpellingContent; answer: AcceptedAnswer }
  | { type: "MATCH"; content: MatchContent; answer: PairsAnswer }
  | { type: "SORT"; content: SortContent; answer: PairsAnswer }
  | { type: "DRAG_DROP"; content: DragDropContent; answer: SequenceAnswer }
  | { type: "READING"; content: ReadingContent; answer: AcceptedAnswer }
  | { type: "WRITING"; content: WritingContent; answer: AcceptedAnswer }
  | { type: "TRACING"; content: TracingContent; answer: CoverageAnswer }
  | { type: "BLEND_SOUNDS"; content: BlendSoundsContent; answer: AcceptedAnswer }
  | { type: "SEGMENT_WORD"; content: SegmentWordContent; answer: SequenceAnswer }
  | { type: "FIND_PATTERN"; content: FindPatternContent; answer: AcceptedAnswer }
  | { type: "SENTENCE_DICTATION"; content: SentenceDictationContent; answer: SentenceAnswer }
  | { type: "READ_PASSAGE"; content: ReadPassageContent; answer: null }
  | { type: "SELECT_ALL"; content: SelectAllContent; answer: SelectAllAnswer }
  | { type: "ORDER_EVENTS"; content: OrderEventsContent; answer: SequenceAnswer };

export type ParseQuestionResult = { ok: true; question: ParsedQuestion } | { ok: false; error: string };

// Validates one question's stored JSON against its type. Also checks cross-field rules
// that a schema alone cannot (a choice answer must name one of the options).
export function parseQuestion(type: string, content: unknown, answer: unknown): ParseQuestionResult {
  if (!isSupportedQuestionType(type)) {
    return { ok: false, error: `unsupported question type ${type}` };
  }
  const schemas = questionTypeSchemas[type];
  const parsedContent = schemas.content.safeParse(content);
  if (!parsedContent.success) {
    return { ok: false, error: `content: ${formatIssues(parsedContent.error)}` };
  }
  if (schemas.answer === null) {
    return { ok: true, question: { type, content: parsedContent.data, answer: null } as ParsedQuestion };
  }
  const parsedAnswer = schemas.answer.safeParse(answer);
  if (!parsedAnswer.success) {
    return { ok: false, error: `answer: ${formatIssues(parsedAnswer.error)}` };
  }
  const question = { type, content: parsedContent.data, answer: parsedAnswer.data } as ParsedQuestion;
  const crossFieldError = checkCrossFields(question);
  return crossFieldError ? { ok: false, error: crossFieldError } : { ok: true, question };
}

function checkCrossFields(q: ParsedQuestion): string | null {
  switch (q.type) {
    case "MULTIPLE_CHOICE":
    case "LISTEN_AND_CHOOSE":
    case "PICTURE_MATCH":
    case "READING":
    case "BLEND_SOUNDS": {
      const ids = new Set(q.content.options.map((o) => o.id));
      if (ids.size !== q.content.options.length) return "option ids must be unique";
      if (!q.answer.accepted.every((id) => ids.has(id))) return "answer must reference an option id";
      if (q.type === "READING" && q.content.format === "true_false" && q.content.options.length !== 2)
        return "a true/false question has exactly two options";
      return null;
    }
    case "MISSING_LETTER": {
      if (!q.answer.accepted.every((a) => q.content.choices.includes(a))) return "answer must be one of the choices";
      const split = q.content.split;
      if (split && split.map((g) => g.grapheme).join("") !== q.content.word.toLowerCase())
        return "the grapheme split must spell the word";
      return null;
    }
    case "WORD_BUILDER": {
      // Every accepted spelling must be buildable from the tiles.
      const joined = q.content.tiles.join("").toLowerCase();
      const unbuildable = q.answer.accepted.find((a) => !containsLetters(joined, a));
      return unbuildable ? `tiles cannot build "${unbuildable}"` : null;
    }
    case "SENTENCE_BUILDER": {
      const tokens = [...q.content.tokens].sort().join("\u0000");
      return q.answer.acceptedSequences.every((s) => [...s].sort().join("\u0000") === tokens)
        ? null
        : "each accepted sequence must use exactly the given tokens";
    }
    case "MATCH": {
      const left = new Set(q.content.left.map((i) => i.id));
      const right = new Set(q.content.right.map((i) => i.id));
      if (left.size !== q.content.left.length || right.size !== q.content.right.length)
        return "item ids must be unique";
      if (q.answer.pairs.length !== left.size) return "every left item needs exactly one pair";
      if (new Set(q.answer.pairs.map((p) => p[0])).size !== left.size) return "a left item is paired twice";
      return q.answer.pairs.every(([l, r]) => left.has(l) && right.has(r))
        ? null
        : "pairs must reference item ids";
    }
    case "SORT": {
      const items = new Set(q.content.items.map((i) => i.id));
      const groups = new Set(q.content.groups.map((g) => g.id));
      if (items.size !== q.content.items.length || groups.size !== q.content.groups.length)
        return "item and group ids must be unique";
      if (q.answer.pairs.length !== items.size || new Set(q.answer.pairs.map((p) => p[0])).size !== items.size)
        return "every item must be sorted into exactly one group";
      return q.answer.pairs.every(([item, group]) => items.has(item) && groups.has(group))
        ? null
        : "pairs must reference item and group ids";
    }
    case "DRAG_DROP": {
      const blanks = q.content.parts.filter((p) => "blank" in p).length;
      const bank = q.content.bank.map((b) => b.toLowerCase());
      for (const seq of q.answer.acceptedSequences) {
        if (seq.length !== blanks) return "each accepted sequence needs one word per blank";
        if (!seq.every((w) => bank.includes(w.toLowerCase()))) return "answers must come from the word bank";
      }
      return null;
    }
    case "SEGMENT_WORD": {
      const ids = new Set(q.content.sounds.map((x) => x.id));
      if (ids.size !== q.content.sounds.length) return "sound ids must be unique";
      for (const seq of q.answer.acceptedSequences) {
        if (seq.length > q.content.maxCount) return "the answer has more sounds than maxCount";
        if (!seq.every((id) => ids.has(id))) return "answers must use the listed sounds";
      }
      return null;
    }
    case "FIND_PATTERN": {
      for (const span of q.answer.accepted) {
        const m = span.match(/^(\d+)-(\d+)$/);
        if (!m) return `"${span}" is not a start-end span`;
        const [start, end] = [Number(m[1]), Number(m[2])];
        if (start > end || end >= q.content.word.length) return `span ${span} is outside "${q.content.word}"`;
        if (q.content.word.slice(start, end + 1) !== q.content.target.toLowerCase())
          return `span ${span} of "${q.content.word}" is not "${q.content.target}"`;
      }
      return null;
    }
    case "SPELLING": {
      const split = q.content.split;
      if (split && split.map((g) => g.grapheme).join("") !== q.answer.accepted[0].toLowerCase())
        return "the grapheme split must spell the first accepted answer";
      if (q.content.mode === "sounds" && !q.content.sounds) return "sounds-to-word needs the sounds to play";
      if (q.content.tiles && !q.answer.accepted.some((a) => containsLetters(q.content.tiles!.join("").toLowerCase(), a)))
        return "the tiles cannot spell the answer";
      if (split && q.content.irregular.some((p) => p >= split.length)) return "irregular position outside the word";
      return null;
    }
    case "SELECT_ALL": {
      const ids = new Set(q.content.options.map((o) => o.id));
      if (ids.size !== q.content.options.length) return "option ids must be unique";
      if (new Set(q.answer.correct).size !== q.answer.correct.length) return "an option is listed twice";
      if (!q.answer.correct.every((id) => ids.has(id))) return "answer must reference option ids";
      return q.answer.correct.length < q.content.options.length ? null : "at least one option must be wrong";
    }
    case "ORDER_EVENTS": {
      const ids = q.content.events.map((e) => e.id);
      if (new Set(ids).size !== ids.length) return "event ids must be unique";
      const sorted = [...ids].sort().join("\u0000");
      for (const seq of q.answer.acceptedSequences)
        if ([...seq].sort().join("\u0000") !== sorted) return "each accepted order must use every event once";
      return q.answer.acceptedSequences.some((seq) => seq.join("\u0000") === ids.join("\u0000"))
        ? "events must not be stored in the right order"
        : null;
    }
    case "SENTENCE_DICTATION":
      return q.answer.accepted.every((a) => a.trim().split(/\s+/).length === q.content.wordCount)
        ? null
        : "wordCount must match the sentence";
    case "WRITING": {
      // The child copies from the word bank, so every answer must be writable from it.
      const bank = new Set(q.content.wordBank.map((w) => w.toLowerCase()));
      const starter = (q.content.starter ?? "").toLowerCase().trim();
      const ok = q.answer.accepted.every((a) => {
        const rest = a.toLowerCase().replace(/[.!?]+$/, "").trim();
        const tail = starter && rest.startsWith(starter) ? rest.slice(starter.length).trim() : rest;
        return tail.split(/\s+/).every((w) => bank.has(w));
      });
      return ok ? null : "writing answers must use words from the word bank";
    }
    default:
      return null;
  }
}

function containsLetters(pool: string, word: string) {
  const counts = new Map<string, number>();
  for (const ch of pool) counts.set(ch, (counts.get(ch) ?? 0) + 1);
  for (const ch of word.toLowerCase()) {
    const n = counts.get(ch) ?? 0;
    if (n === 0) return false;
    counts.set(ch, n - 1);
  }
  return true;
}

function formatIssues(error: z.ZodError) {
  return error.issues.map((i) => `${i.path.join(".") || "(root)"} ${i.message}`).join("; ");
}
